version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - vlr_network

  vlrapi2:
    image: vlrapi2
    ports:
      - 9091:9091
    networks:
      - vlr_network
    links:
      - redis
    environment:
      - DB_URI=redis://redis:6379

networks:
  vlr_network:
